# Generated by Django 4.1.3 on 2022-11-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='first1',
            new_name='login1',
        ),
    ]
