# Generated by Django 4.1.1 on 2022-12-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_delete_login1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.IntegerField(default=5),
        ),
    ]
